export const sampleProperties = [
  {
    name: 'Modern Glass Estate',
    description: 'Stunning contemporary home with floor-to-ceiling windows and minimalist design. Perfect for luxury lifestyle shoots and modern architectural photography.',
    address: '1234 Highland Park Ave',
    city: 'Dallas',
    county: 'Dallas County',
    zipcode: '75205',
    property_type: 'Residential',
    square_footage: 4500,
    lot_size: 0.75,
    bedrooms: 4,
    bathrooms: 3.5,
    parking_spaces: 3,
    year_built: 2020,
    features: ['Pool', 'Kitchen', 'Parking', 'Garage', 'Patio Balconies', 'Garden'],
    categories: ['Modern', 'New', 'Luxury'],
    permits_available: true,
    permit_details: 'Full filming permits available. HOA approval required 2 weeks in advance.',
    daily_rate: 2500,
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80'],
    primary_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
    status: 'active',
  },
  {
    name: 'Historic Victorian Mansion',
    description: 'Beautifully preserved Victorian mansion with original woodwork and period details. Ideal for period pieces and historical dramas.',
    address: '789 Heritage Lane',
    city: 'Fort Worth',
    county: 'Tarrant County',
    zipcode: '76102',
    property_type: 'Residential',
    square_footage: 6000,
    lot_size: 1.2,
    bedrooms: 6,
    bathrooms: 4,
    parking_spaces: 4,
    year_built: 1895,
    features: ['Fireplace', 'Garden', 'Driveway', 'Hardwood Floors'],
    categories: ['Historical', 'Luxury'],
    permits_available: true,
    permit_details: 'Available for filming. Historical preservation guidelines must be followed.',
    daily_rate: 3000,
    images: ['https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&q=80'],
    primary_image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&q=80',
    status: 'active',
  },
  {
    name: 'Industrial Warehouse Loft',
    description: 'Raw industrial space with exposed brick, high ceilings, and dramatic natural light. Perfect for urban scenes and edgy productions.',
    address: '456 Industrial Blvd',
    city: 'Dallas',
    county: 'Dallas County',
    zipcode: '75226',
    property_type: 'Commercial',
    square_footage: 8000,
    lot_size: 0.5,
    bedrooms: null,
    bathrooms: 2,
    parking_spaces: 10,
    year_built: 1960,
    features: ['Parking', 'Kitchen'],
    categories: ['Industrial', 'Commercial'],
    permits_available: true,
    permit_details: 'Commercial filming permits available.',
    daily_rate: 1800,
    images: ['https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=1200&q=80'],
    primary_image: 'https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=1200&q=80',
    status: 'active',
  },
  {
    name: 'Lakeside Ranch Property',
    description: 'Expansive ranch property with private lake, rolling hills, and rustic charm. Great for outdoor scenes and Western themes.',
    address: '2000 Ranch Road',
    city: 'Denton',
    county: 'Denton County',
    zipcode: '76201',
    property_type: 'Residential',
    square_footage: 3200,
    lot_size: 15.0,
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 6,
    year_built: 1985,
    features: ['Garden', 'Driveway', 'Fireplace'],
    categories: ['Natural', 'Residential'],
    permits_available: true,
    permit_details: 'Open land available for productions.',
    daily_rate: 2200,
    images: ['https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&q=80'],
    primary_image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&q=80',
    status: 'active',
  },
  {
    name: 'Downtown High-Rise Penthouse',
    description: 'Luxurious penthouse with panoramic city views and contemporary design. Perfect for upscale urban scenes.',
    address: '1500 Main Street, Suite 4000',
    city: 'Dallas',
    county: 'Dallas County',
    zipcode: '75201',
    property_type: 'Residential',
    square_footage: 3800,
    lot_size: null,
    bedrooms: 3,
    bathrooms: 3,
    parking_spaces: 2,
    year_built: 2018,
    features: ['Patio Balconies', 'Kitchen', 'Parking', 'Fireplace'],
    categories: ['Modern', 'Luxury'],
    permits_available: true,
    permit_details: 'Building management approval required.',
    daily_rate: 3500,
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80'],
    primary_image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
    status: 'active',
  },
  {
    name: 'Mid-Century Modern Home',
    description: 'Authentic mid-century modern architecture with clean lines and vintage appeal. Excellent for retro-themed productions.',
    address: '890 Retro Drive',
    city: 'Arlington',
    county: 'Tarrant County',
    zipcode: '76010',
    property_type: 'Residential',
    square_footage: 2400,
    lot_size: 0.4,
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 2,
    year_built: 1965,
    features: ['Pool', 'Kitchen', 'Parking', 'Patio Balconies'],
    categories: ['Modern', 'Residential'],
    permits_available: true,
    permit_details: 'Available for filming.',
    daily_rate: 1500,
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80'],
    primary_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
    status: 'active',
  },
];

export async function seedDatabase(supabase: any) {
  console.log('Seeding database with sample properties...');

  for (const property of sampleProperties) {
    const { error } = await supabase
      .from('properties')
      .insert(property);

    if (error) {
      console.error('Error inserting property:', error);
    }
  }

  console.log('Database seeded successfully!');
}
